//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxiCallCenter.MVP.WpfApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OrderDialogResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OrderDialogResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TaxiCallCenter.MVP.WpfApp.Resources.OrderDialogResources", typeof(OrderDialogResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Здравствуйте, заказ такси Пилот приветствует Вас! Я - робот Лера, готова принять Ваш заказ! Вы готовы к оформлению заказа такси? Да. Или. Нет..
        /// </summary>
        internal static string Greeting01 {
            get {
                return ResourceManager.GetString("Greeting01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не могу распознать ваш ответ. Вы готовы к оформлению заказа такси? Да. Или. Нет..
        /// </summary>
        internal static string GreetingFailed01 {
            get {
                return ResourceManager.GetString("GreetingFailed01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не могу распознать ваш ответ. До свидания..
        /// </summary>
        internal static string GreetingFailed02 {
            get {
                return ResourceManager.GetString("GreetingFailed02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если ваш вопрос адресован оператору службы заказа такси, нажмите один. Если у вас есть вопрос по пропаже вещей или жалоба - нажмите два..
        /// </summary>
        internal static string NotOrder01 {
            get {
                return ResourceManager.GetString("NotOrder01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расскажите ваши пожелания. Они будут переданы водителю..
        /// </summary>
        internal static string OrderAdditionalInfo01 {
            get {
                return ResourceManager.GetString("OrderAdditionalInfo01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не могу распознать ваш ответ. Расскажите ваши пожелания. Они будут переданы водителю..
        /// </summary>
        internal static string OrderAdditionalInfoFailed01 {
            get {
                return ResourceManager.GetString("OrderAdditionalInfoFailed01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не могу распознать ваш ответ. До свидания..
        /// </summary>
        internal static string OrderAdditionalInfoFailed02 {
            get {
                return ResourceManager.GetString("OrderAdditionalInfoFailed02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У вас есть пожелания к заказу? Да. Или. Нет..
        /// </summary>
        internal static string OrderAdditionalInfoRequest01 {
            get {
                return ResourceManager.GetString("OrderAdditionalInfoRequest01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не могу распознать ваш ответ. У вас есть пожелания к заказу? Да. Или. Нет..
        /// </summary>
        internal static string OrderAdditionalInfoRequestFailed01 {
            get {
                return ResourceManager.GetString("OrderAdditionalInfoRequestFailed01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не могу распознать ваш ответ. До свидания..
        /// </summary>
        internal static string OrderAdditionalInfoRequestFailed02 {
            get {
                return ResourceManager.GetString("OrderAdditionalInfoRequestFailed02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш телефон звонящий? Да. Или. Нет..
        /// </summary>
        internal static string OrderCallerPhoneConfirm01 {
            get {
                return ResourceManager.GetString("OrderCallerPhoneConfirm01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не могу распознать ваш ответ. Ваш телефон звонящий? Да. Или. Нет..
        /// </summary>
        internal static string OrderCallerPhoneConfirmFailed01 {
            get {
                return ResourceManager.GetString("OrderCallerPhoneConfirmFailed01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не могу распознать ваш ответ. До свидания..
        /// </summary>
        internal static string OrderCallerPhoneConfirmFailed02 {
            get {
                return ResourceManager.GetString("OrderCallerPhoneConfirmFailed02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш заказ принят. До свидания..
        /// </summary>
        internal static string OrderCreated01 {
            get {
                return ResourceManager.GetString("OrderCreated01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уточните дату и время, на которые принять заказ..
        /// </summary>
        internal static string OrderCustomDateTime01 {
            get {
                return ResourceManager.GetString("OrderCustomDateTime01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не могу распознать ваш ответ. Уточните дату и время, на которые принять заказ..
        /// </summary>
        internal static string OrderCustomDateTimeFailed01 {
            get {
                return ResourceManager.GetString("OrderCustomDateTimeFailed01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не могу распознать ваш ответ. До свидания..
        /// </summary>
        internal static string OrderCustomDateTimeFailed02 {
            get {
                return ResourceManager.GetString("OrderCustomDateTimeFailed02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Откуда поедем?.
        /// </summary>
        internal static string OrderFrom01 {
            get {
                return ResourceManager.GetString("OrderFrom01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автомобиль будет подан по адресу {0}. Все верно? Да. Или. Нет..
        /// </summary>
        internal static string OrderFromConfirm01 {
            get {
                return ResourceManager.GetString("OrderFromConfirm01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не могу распознать ваш ответ. Автомобиль будет подан по адресу {0}. Всё верно? Да. Или. Нет..
        /// </summary>
        internal static string OrderFromConfirmFailed01 {
            get {
                return ResourceManager.GetString("OrderFromConfirmFailed01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не могу распознать ваш ответ. До свидания..
        /// </summary>
        internal static string OrderFromConfirmFailed02 {
            get {
                return ResourceManager.GetString("OrderFromConfirmFailed02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не могу распознать ваш ответ. Уточните адрес, куда подать автомобиль..
        /// </summary>
        internal static string OrderFromFailed01 {
            get {
                return ResourceManager.GetString("OrderFromFailed01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не могу распознать ваш ответ. До свидания..
        /// </summary>
        internal static string OrderFromFailed02 {
            get {
                return ResourceManager.GetString("OrderFromFailed02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уточните адрес, куда подать автомобиль..
        /// </summary>
        internal static string OrderFromNotConfirmed01 {
            get {
                return ResourceManager.GetString("OrderFromNotConfirmed01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заказ принимается на ближайшее время? Да. Или. Нет..
        /// </summary>
        internal static string OrderNowConfirm01 {
            get {
                return ResourceManager.GetString("OrderNowConfirm01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не могу распознать ваш ответ. Заказ принимается на ближайшее время? Да. Или. Нет..
        /// </summary>
        internal static string OrderNowConfirmFailed01 {
            get {
                return ResourceManager.GetString("OrderNowConfirmFailed01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не могу распознать ваш ответ. До свидания..
        /// </summary>
        internal static string OrderNowConfirmFailed02 {
            get {
                return ResourceManager.GetString("OrderNowConfirmFailed02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назовите отчетливо номер телефона для оформления заказа..
        /// </summary>
        internal static string OrderPhoneRequest01 {
            get {
                return ResourceManager.GetString("OrderPhoneRequest01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не могу распознать ваш ответ. Назовите отчетливо номер телефона для оформления заказа..
        /// </summary>
        internal static string OrderPhoneRequestFailed01 {
            get {
                return ResourceManager.GetString("OrderPhoneRequestFailed01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не могу распознать ваш ответ. До свидания..
        /// </summary>
        internal static string OrderPhoneRequestFailed02 {
            get {
                return ResourceManager.GetString("OrderPhoneRequestFailed02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Куда поедем?.
        /// </summary>
        internal static string OrderTo01 {
            get {
                return ResourceManager.GetString("OrderTo01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поедем по адресу {0}. Все верно? Да. Или. Нет..
        /// </summary>
        internal static string OrderToConfirm01 {
            get {
                return ResourceManager.GetString("OrderToConfirm01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не могу распознать ваш ответ. Поедем по адресу {0}. Всё верно? Да. Или. Нет..
        /// </summary>
        internal static string OrderToConfirmFailed01 {
            get {
                return ResourceManager.GetString("OrderToConfirmFailed01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не могу распознать ваш ответ. До свидания..
        /// </summary>
        internal static string OrderToConfirmFailed02 {
            get {
                return ResourceManager.GetString("OrderToConfirmFailed02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заказ принимается на сегодня? Да. Или. Нет..
        /// </summary>
        internal static string OrderTodayConfirm01 {
            get {
                return ResourceManager.GetString("OrderTodayConfirm01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не могу распознать ваш ответ. Заказ принимается на сегодня? Да. Или. Нет..
        /// </summary>
        internal static string OrderTodayConfirmFailed01 {
            get {
                return ResourceManager.GetString("OrderTodayConfirmFailed01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не могу распознать ваш ответ. До свидания..
        /// </summary>
        internal static string OrderTodayConfirmFailed02 {
            get {
                return ResourceManager.GetString("OrderTodayConfirmFailed02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уточните время, на которое принять заказ..
        /// </summary>
        internal static string OrderTodayTime01 {
            get {
                return ResourceManager.GetString("OrderTodayTime01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не могу распознать ваш ответ. Уточните время, на которое принять заказ..
        /// </summary>
        internal static string OrderTodayTimeFailed01 {
            get {
                return ResourceManager.GetString("OrderTodayTimeFailed01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не могу распознать ваш ответ. До свидания..
        /// </summary>
        internal static string OrderTodayTimeFailed02 {
            get {
                return ResourceManager.GetString("OrderTodayTimeFailed02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не могу распознать ваш ответ. Уточните адрес, куда поедем..
        /// </summary>
        internal static string OrderToFailed01 {
            get {
                return ResourceManager.GetString("OrderToFailed01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не могу распознать ваш ответ. До свидания..
        /// </summary>
        internal static string OrderToFailed02 {
            get {
                return ResourceManager.GetString("OrderToFailed02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уточните адрес, куда поедем..
        /// </summary>
        internal static string OrderToNotConfirmed01 {
            get {
                return ResourceManager.GetString("OrderToNotConfirmed01", resourceCulture);
            }
        }
    }
}
